# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
        ('actividad_economica', '0001_initial'),
        ('jornada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadaclass',
            name='actividad_economica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividad_economica.ActividadEconomicaClass'),
        ),
        migrations.AddField(
            model_name='jornadaclass',
            name='horario',
            field=models.ManyToManyField(to='horario.HorarioClass'),
        ),
        migrations.AddField(
            model_name='jornadaclass',
            name='region',
            field=models.CharField(choices=[('RAP', 'Arica y Parinacota'), ('RTP', 'Tarapacá'), ('RAN', 'Antofagasta'), ('RAT', 'Atacama'), ('RCO', 'Coquimbo'), ('RVA', 'Valparaíso'), ('RME', 'Metropolitana'), ('ROH', 'O’Higgins'), ('RMA', 'Maule'), ('RBI', 'Biobío'), ('RAR', 'Araucanía'), ('RLR', 'Los Ríos'), ('RLL', 'Los Lagos'), ('RLL', 'Aysén'), ('RMG', 'Magallanes')], default=('RAP', 'Arica y Parinacota'), max_length=3),
        ),
        migrations.AddField(
            model_name='jornadaclass',
            name='tipo_empresa',
            field=models.CharField(choices=[('ME', 'Micro Empresa'), ('PE', 'Pequena Empresa'), ('ME', 'Mediana Empresa'), ('GE', 'Gran Empresa')], default=('ME', 'Micro Empresa'), max_length=2),
        ),
        migrations.AlterField(
            model_name='jornadaclass',
            name='tipo',
            field=models.CharField(choices=[('jc', 'Jornada Completa'), ('jp', 'Jornada Parcial'), ('j180h', '180 horas mensuales'), ('j45h', '45 horas semanales'), ('j60h', '60 horas semanales'), ('jadt', 'Autorizada por la Dirección del Trabajo'), ('jb', 'Bisemanal'), ('jra', 'Registro de Asistencia')], default=('jc', 'Jornada Completa'), max_length=6),
        ),
    ]
