# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0003_auto_20190309_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadaclass',
            name='descripcion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
