# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomicaClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
